%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#ffffff', 'primaryTextColor': '#000000', 'primaryBorderColor': '#000000', 'lineColor': '#000000', 'fontFamily': 'Times New Roman'}}}%%
erDiagram
    АВТОМОБИЛИ {
        int Код_Auto PK
        string Наименование
        string ГосНомер
        string Марка
        string Модель
        int ГодВыпуска
        string Цвет
        string ТипКПП
        string Статус
    }

    КЛИЕНТЫ {
        int Код_Клиента PK
        string ФИО
        date ДатаРождения
        string НомерВУ
        string Телефон
        string Адрес
    }

    ЦЕНЫ_ПРОКАТА {
        int Код_Цены PK
        int Код_Auto FK
        decimal ЦенаЗаСутки
    }

    ДОГОВОР_АРЕНДЫ {
        int Номер PK
        date Дата
        int Код_Клиента FK
        int Код_Auto FK
        date ДатаНачала
        date ДатаОкончания
        decimal ЦенаЗаСутки
        decimal СуммаЗалога
    }

    ЗАКРЫТИЕ_АРЕНДЫ {
        int Номер PK
        date Дата
        int Номер_Договора FK
        date ДатаВозврата
        int ПробегФакт
        decimal ДопРасходы
        int КоличествоСуток
        decimal ИтоговаяСумма
    }

    СТАТУС_АВТОПАРКА {
        int Код_Auto FK
        string Статус
        date Период
    }

    ДОХОДЫ_ПРОКАТА {
        int Номер_Договора FK
        decimal Выручка
        date Период
    }

    АВТОМОБИЛИ ||--o{ ЦЕНЫ_ПРОКАТА : "имеет"
    КЛИЕНТЫ ||--o{ ДОГОВОР_АРЕНДЫ : "заключает"
    АВТОМОБИЛИ ||--o{ ДОГОВОР_АРЕНДЫ : "сдаётся"
    ДОГОВОР_АРЕНДЫ ||--o| ЗАКРЫТИЕ_АРЕНДЫ : "завершается"
    АВТОМОБИЛИ ||--o{ СТАТУС_АВТОПАРКА : "учитывается"
    ДОГОВОР_АРЕНДЫ ||--o{ ДОХОДЫ_ПРОКАТА : "формирует"
